name: github-actions-2
on: push
jobs:
    job_1:
        name: job-1
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: list all files
              run: ls

            - name: read readme file
              run: cat README.md